
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bashir Ebrahimi
 */
public class JavaPOS extends javax.swing.JFrame {

    /**
     * Creates new form JavaPOS
     */
    public JavaPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtnc = new javax.swing.JButton();
        jbtndot = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jbntCoffee = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jbtnRainBowCake = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtDesplay = new javax.swing.JTextField();
        jtxtChange = new javax.swing.JTextField();
        jcboPyment = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jtxtBarCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn9.setBackground(new java.awt.Color(51, 51, 51));
        jbtn9.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 100, 110));

        jbtn7.setBackground(new java.awt.Color(51, 51, 51));
        jbtn7.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 110));

        jbtn8.setBackground(new java.awt.Color(51, 51, 51));
        jbtn8.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 100, 110));

        jbtn4.setBackground(new java.awt.Color(51, 51, 51));
        jbtn4.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 110));

        jbtn5.setBackground(new java.awt.Color(51, 51, 51));
        jbtn5.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 100, 110));

        jbtn6.setBackground(new java.awt.Color(51, 51, 51));
        jbtn6.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 100, 110));

        jbtn3.setBackground(new java.awt.Color(51, 51, 51));
        jbtn3.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 100, 110));

        jbtn2.setBackground(new java.awt.Color(51, 51, 51));
        jbtn2.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 100, 110));

        jbtn1.setBackground(new java.awt.Color(51, 51, 51));
        jbtn1.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, 110));

        jbtnc.setBackground(new java.awt.Color(51, 51, 51));
        jbtnc.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jbtnc.setText("C");
        jbtnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 100, 100));

        jbtndot.setBackground(new java.awt.Color(51, 51, 51));
        jbtndot.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jbtndot.setText(".");
        jbtndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndotActionPerformed(evt);
            }
        });
        jPanel1.add(jbtndot, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 100, 100));

        jbtn0.setBackground(new java.awt.Color(51, 51, 51));
        jbtn0.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 100, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 340, 480));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton14.setBackground(new java.awt.Color(0, 153, 153));
        jButton14.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fast-food-restaurant-menu-price-cards-vector-19355625.jpg"))); // NOI18N
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 110));

        jbntCoffee.setBackground(new java.awt.Color(0, 153, 153));
        jbntCoffee.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jbntCoffee.setForeground(new java.awt.Color(255, 255, 255));
        jbntCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fast-food-restaurant-menu-price-cards-vector-15863740 (1).png"))); // NOI18N
        jbntCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntCoffeeActionPerformed(evt);
            }
        });
        jPanel2.add(jbntCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 110));

        jButton16.setBackground(new java.awt.Color(0, 153, 153));
        jButton16.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fast-food-restaurant-menu-price-cards-vector-15863740.png"))); // NOI18N
        jPanel2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 110));

        jButton17.setBackground(new java.awt.Color(0, 153, 153));
        jButton17.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fast-food-restaurant-menu-price-cards-vector-15863740 (1).png"))); // NOI18N
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 110, 110));

        jButton18.setBackground(new java.awt.Color(0, 153, 153));
        jButton18.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fast-food-restaurant-menu-price-cards-vector-15863740 (1).png"))); // NOI18N
        jPanel2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 110, 110));

        jButton19.setBackground(new java.awt.Color(0, 153, 153));
        jButton19.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fast-food-restaurant-menu-price-cards-vector-15863740 (1).png"))); // NOI18N
        jPanel2.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 110, 110));

        jButton20.setBackground(new java.awt.Color(0, 153, 153));
        jButton20.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fast-food-restaurant-menu-price-cards-vector-15863740 (1).png"))); // NOI18N
        jPanel2.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 110, 110));

        jButton21.setBackground(new java.awt.Color(0, 153, 153));
        jButton21.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fast-food-restaurant-menu-price-cards-vector-15863740 (1).png"))); // NOI18N
        jPanel2.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 110, 110));

        jButton22.setBackground(new java.awt.Color(0, 153, 153));
        jButton22.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fast-food-restaurant-menu-price-cards-vector-15863740 (1).png"))); // NOI18N
        jPanel2.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 110, 110));

        jButton23.setBackground(new java.awt.Color(0, 153, 153));
        jButton23.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fast-food-restaurant-menu-price-cards-vector-15863740 (1).png"))); // NOI18N
        jPanel2.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 110, 110));

        jbtnRainBowCake.setBackground(new java.awt.Color(0, 153, 153));
        jbtnRainBowCake.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jbtnRainBowCake.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRainBowCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fast-food-restaurant-menu-price-cards-vector-15863740 (1).png"))); // NOI18N
        jbtnRainBowCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRainBowCakeActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnRainBowCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 110, 110));

        jButton25.setBackground(new java.awt.Color(0, 153, 153));
        jButton25.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fast-food-restaurant-menu-price-cards-vector-15863740 (1).png"))); // NOI18N
        jPanel2.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 110));

        jButton26.setBackground(new java.awt.Color(0, 153, 153));
        jButton26.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jButton26.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 110, 110));

        jButton27.setBackground(new java.awt.Color(0, 153, 153));
        jButton27.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setToolTipText("");
        jPanel2.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 110, 110));

        jButton28.setBackground(new java.awt.Color(0, 153, 153));
        jButton28.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jButton28.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 110, 110));

        jButton29.setBackground(new java.awt.Color(0, 153, 153));
        jButton29.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jButton29.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 110, 110));

        jButton30.setBackground(new java.awt.Color(0, 153, 153));
        jButton30.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jButton30.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 110, 110));

        jButton31.setBackground(new java.awt.Color(0, 153, 153));
        jButton31.setFont(new java.awt.Font("Zilla Slab", 1, 48)); // NOI18N
        jButton31.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 110, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 730, 480));

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 280, 420));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Total");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Sub Total");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 18, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Tax");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jtxtTotal.setBackground(new java.awt.Color(51, 51, 51));
        jtxtTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtTotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 170, -1));

        jtxtSubTotal.setBackground(new java.awt.Color(51, 51, 51));
        jtxtSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 170, -1));

        jtxtTax.setBackground(new java.awt.Color(51, 51, 51));
        jtxtTax.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtTax.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 170, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 200));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Change");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Cash");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Pyment Method");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 18, -1, -1));

        jtxtDesplay.setBackground(new java.awt.Color(51, 51, 51));
        jtxtDesplay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtDesplay.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jtxtDesplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 180, -1));

        jtxtChange.setBackground(new java.awt.Color(51, 51, 51));
        jtxtChange.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtChange.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 180, -1));

        jcboPyment.setBackground(new java.awt.Color(51, 51, 51));
        jcboPyment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcboPyment.setForeground(new java.awt.Color(255, 255, 255));
        jcboPyment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card" }));
        jPanel5.add(jcboPyment, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 180, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 460, 200));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setBackground(new java.awt.Color(51, 51, 51));
        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnReset.setForeground(new java.awt.Color(255, 255, 255));
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 190, 50));

        jbtnPay.setBackground(new java.awt.Color(51, 51, 51));
        jbtnPay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPay.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 50));

        jbtnPrint.setBackground(new java.awt.Color(51, 51, 51));
        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPrint.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, 50));

        jbtnExit.setBackground(new java.awt.Color(51, 51, 51));
        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(255, 255, 255));
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 320, 50));

        jbtnRemove.setBackground(new java.awt.Color(51, 51, 51));
        jbtnRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnRemove.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 190, 50));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 430, 200));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 1370, 220));

        jtxtBarCode.setBackground(new java.awt.Color(51, 51, 51));
        jtxtBarCode.setFont(new java.awt.Font("Libre Barcode 128", 1, 48)); // NOI18N
        jtxtBarCode.setForeground(new java.awt.Color(255, 255, 255));
        jtxtBarCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBarCode.setToolTipText("");
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 280, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    ============================ Function =============================================
    public void ItemCost()
    {
        double sum = 0;
        for(int i = 0; i <jTable1.getRowCount(); i ++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        jtxtSubTotal.setText(Double.toString(sum));
        double cTota11 = Double.parseDouble(jtxtSubTotal.getText());
        
        double cTax = (cTota11 * 3.9)/100;
        
        String iTaxTotal = String.format("$ %.2f", cTax);
        jtxtTax.setText(iTaxTotal);
        
        String iSubTotal = String.format("$ %.2f", cTota11);
        jtxtSubTotal.setText(iSubTotal);
        
        String iTotal = String.format("$ %.2f", cTota11 + cTax);
        jtxtTotal.setText(iTotal);
        
        String BarCode = String.format("Total is  %.2f", cTota11 + cTax);
        jtxtBarCode.setText(BarCode);
        
    }
  //    ============================ Function =============================================

    public void Change()
    {
        double sum = 0;
        double tax = 3.9;
        double cash = Double.parseDouble(jtxtDesplay.getText());
        
        for(int i = 0; i <jTable1.getRowCount(); i ++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        
        double cTax = (sum * 3.9 )/100;
        double cChange = (cash - (sum + cTax));
        
        String ChangeGiven = String.format("$ %.2f", cChange);
        jtxtChange.setText(ChangeGiven);
         
        
    }
    
    
    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String Enternumber = jtxtDesplay.getText();
        
        if(Enternumber == ""){
            jtxtDesplay.setText(jbtn8.getText());
        }else
        {
            Enternumber = jtxtDesplay.getText() + jbtn8.getText();
            jtxtDesplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbntCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntCoffeeActionPerformed
         double priceofItem = 5.40;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Coffee","1",priceofItem});
        ItemCost();
    }//GEN-LAST:event_jbntCoffeeActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        String Enternumber = jtxtDesplay.getText();
        
        if(Enternumber == ""){
            jtxtDesplay.setText(jbtn7.getText());
        }else
        {
            Enternumber = jtxtDesplay.getText() + jbtn7.getText();
            jtxtDesplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
      String Enternumber = jtxtDesplay.getText();
        
        if(Enternumber == ""){
            jtxtDesplay.setText(jbtn9.getText());
        }else
        {
            Enternumber = jtxtDesplay.getText() + jbtn9.getText();
            jtxtDesplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        String Enternumber = jtxtDesplay.getText();
        
        if(Enternumber == ""){
            jtxtDesplay.setText(jbtn4.getText());
        }else
        {
            Enternumber = jtxtDesplay.getText() + jbtn4.getText();
            jtxtDesplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
      String Enternumber = jtxtDesplay.getText();
        
        if(Enternumber == ""){
            jtxtDesplay.setText(jbtn5.getText());
        }else
        {
            Enternumber = jtxtDesplay.getText() + jbtn5.getText();
            jtxtDesplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
         String Enternumber = jtxtDesplay.getText();
        
        if(Enternumber == ""){
            jtxtDesplay.setText(jbtn6.getText());
        }else
        {
            Enternumber = jtxtDesplay.getText() + jbtn6.getText();
            jtxtDesplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        String Enternumber = jtxtDesplay.getText();
        
        if(Enternumber == ""){
            jtxtDesplay.setText(jbtn1.getText());
        }else
        {
            Enternumber = jtxtDesplay.getText() + jbtn1.getText();
            jtxtDesplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        String Enternumber = jtxtDesplay.getText();
        
        if(Enternumber == ""){
            jtxtDesplay.setText(jbtn2.getText());
        }else
        {
            Enternumber = jtxtDesplay.getText() + jbtn2.getText();
            jtxtDesplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
       String Enternumber = jtxtDesplay.getText();
        
        if(Enternumber == ""){
            jtxtDesplay.setText(jbtn3.getText());
        }else
        {
            Enternumber = jtxtDesplay.getText() + jbtn3.getText();
            jtxtDesplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
       String Enternumber = jtxtDesplay.getText();
        
        if(Enternumber == ""){
            jtxtDesplay.setText(jbtn0.getText());
        }else 
        {
            Enternumber = jtxtDesplay.getText() + jbtn0.getText();
            jtxtDesplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncActionPerformed
       jtxtDesplay.setText("");
       jtxtChange.setText("");
    }//GEN-LAST:event_jbtncActionPerformed

    private void jbtndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndotActionPerformed
       if(!jtxtDesplay.getText().contains("."))
       {
           jtxtDesplay.setText(jtxtDesplay.getText() + jbtndot.getText());
       }
    }//GEN-LAST:event_jbtndotActionPerformed

    private void jbtnRainBowCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRainBowCakeActionPerformed
       
        double priceofItem = 3.40;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"RainBow Cake","1",priceofItem});
        ItemCost();
    }//GEN-LAST:event_jbtnRainBowCakeActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        if (jcboPyment.getSelectedItem().equals("Cash")) 
        {
            Change();
            
        }else
        {
            jtxtChange.setText("");
            jtxtDesplay.setText("");
            
        }
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
      DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
      model.setRowCount(0);
      jtxtChange.setText("");
      jtxtTax.setText("");
      jtxtSubTotal.setText("");
      jtxtDesplay.setText("");
      jtxtBarCode.setText("");
      jtxtTotal.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
       
        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page, {0, number, Integer}");
        
        try 
        {
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        }
        
        catch (java.awt.print.PrinterException e) {
            System.err.format("No Printing found", e.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
      DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
      int RemoveItem = jTable1.getSelectedRow();
        if (RemoveItem >=0 ) {
            model.removeRow(RemoveItem);
        }
        ItemCost();
        
         if (jcboPyment.getSelectedItem().equals("Cash")) 
        {
            Change();
            
        }else
        {
            jtxtChange.setText("");
            jtxtDesplay.setText("");
            
        }
    }//GEN-LAST:event_jbtnRemoveActionPerformed
private JFrame freame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
       
        freame = new JFrame("Exit");
       if(JOptionPane.showConfirmDialog(freame,"Confirm if you want to exit","Point of Sale",
               JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
       {
           System.exit(0);
       }
    }//GEN-LAST:event_jbtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaPOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbntCoffee;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRainBowCake;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnc;
    private javax.swing.JButton jbtndot;
    private javax.swing.JComboBox<String> jcboPyment;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDesplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
